name: .NET 6

on:
  workflow_dispatch:
    inputs:
      build_config:
        type: choice
        required: true
        default: 'Release'
        description: Build configuration
        options:
        - Debug
        - Release
      arch_config:
        type: choice
        required: true
        default: 'x86'
        description: Target architecture
        options:
        - x86
        - x64
        - arm
        - arm64

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: >
          foreach ($f in Get-ChildItem ${{ github.workspace }} -Recurse -Filter *.csproj) {
          dotnet build $f.FullName -a ${{ github.event.inputs.arch_config }} -c ${{ github.event.inputs.build_config }} 
          }
